services:
  xiaoya-alist:
    image: 'ghcr.io/monlor/xiaoya-alist:{{ XIAOYA_ALIST_TAG }}'
    volumes:
      - '{{ XIAOYA_ALIST_DATA_PATH | mkdir | chown }}:/data'
    environment:
#   {% for key in container.items -%}
#   {% with value = config.get('XIAOYA_ALIST_'+key, default=container.items[key]) %}
      - '{{ key }}={{ value }}'
#   {% endwith %}
#   {%- endfor %}
#   {% if XIAOYA_ALIST_EXPOSE_PORT > 0 %}
    ports:
      - '{{ XIAOYA_ALIST_EXPOSE_PORT }}:5678'
#   {% endif %}
    networks:
      - nginx

networks:
  nginx:
    name: nginx
