services:
  xiaoya-alist:
    image: 'image: ghcr.io/monlor/xiaoya-alist:{{ XIAOYA_ALIST_TAG }}'
    volumes:
      - '{{ XIAOYA_ALIST_DATA_PATH | mkdir | chown }}:/data'
    environment:
      - 'IDENT=ice-black-tea'
#   { % for key in container.keys -% }
#   { % with value = config.get(key, default=None) -% }
#   { % if value % }
      - '{{ key }}={{ value }}'
#   {% endif %}
#   {%- endwith %}
#   {%- endfor %}
#   {% if XIAOYA_ALIST_EXPOSE_PORT > 0 %}
    ports:
      - '{{ XIAOYA_ALIST_EXPOSE_PORT }}:5678'
#   {% endif %}
    networks:
      - nginx

networks:
  nginx:
    name: nginx
