services:
  gitlab:
    image: gitlab/gitlab-ce:{{ GITLAB_TAG }}
    environment:
      GITLAB_ROOT_PASSWORD: '{{ GITLAB_ROOT_PASSWORD }}'
      GITLAB_OMNIBUS_CONFIG: |
          external_url 'https://{{ GITLAB_DOMAIN }}:{{ HTTPS_PORT }}'
          gitlab_rails['gitlab_shell_ssh_port'] = {{ GITLAB_SSH_PORT }}

          nginx['enable'] = true
          nginx['listen_port'] = 80
          nginx['listen_https'] = false

          postgresql['enable'] = false
          gitlab_rails['db_adapter'] = "postgresql"
          gitlab_rails['db_encoding'] = "utf8"
          gitlab_rails['db_host'] = "{{ GITLAB_DB_HOST }}"
          gitlab_rails['db_port'] = "{{ GITLAB_DB_PORT }}"
          gitlab_rails['db_database'] = "{{ GITLAB_DB_DATABASE }}"
          gitlab_rails['db_username'] = "{{ GITLAB_DB_USERNAME }}"
          gitlab_rails['db_password'] = "{{ GITLAB_DB_PASSWORD }}"

          letsencrypt['enable'] = false
          registry['enable'] = false

          # 关闭监控
          prometheus['enable'] = false
          alertmanager['enable'] = false
          node_exporter['enable'] = false
          redis_exporter['enable'] = false
          postgres_exporter['enable'] = false
          pgbouncer_exporter['enable'] = false
          gitlab_exporter['enable'] = false
          prometheus_monitoring['enable'] = false
          # grafana['enable'] = false
          sidekiq['metrics_enabled'] = false

          # 禁用 PUMA 集群模式
          puma['worker_processes'] = 0
          puma['min_threads'] = 1
          puma['max_threads'] = 2

          # 降低后台守护进程并发数
          sidekiq['concurrency'] = 5

          gitlab_ci['gitlab_ci_all_broken_builds'] = false
          gitlab_ci['gitlab_ci_add_pusher'] = false

          # Usage Statistics
          gitlab_rails['usage_ping_enabled'] = false
          gitlab_rails['sentry_enabled'] = false
          # grafana['reporting_enabled'] = false

    ports:
      - '{{ GITLAB_SSH_PORT }}:22'
    volumes:
      - '{{ mkdir(APP_PATH/"config") | chown }}:/etc/gitlab'
      - '{{ mkdir(APP_PATH/"logs") | chown }}:/var/log/gitlab'
      - '{{ mkdir(APP_PATH/"data") | chown }}:/var/opt/gitlab'
      - '{{ mkdir(APP_DATA_PATH/"data"/"git-data") | chown }}:/var/opt/gitlab/git-data'
    networks:
      - nginx
      - gitlab
#   {% if GITLAB_DB_HOST == 'gitlab-postgres' %}
    depends_on:
      - gitlab-postgres
#   {% endif %}

#   {% if GITLAB_DB_HOST == 'gitlab-postgres' %}
  gitlab-postgres:
    image: postgres:16-alpine
    volumes:
      - '{{ mkdir(APP_PATH/"postgres") | chown }}:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: '{{ GITLAB_DB_DATABASE }}'
      POSTGRES_USER: '{{ GITLAB_DB_USERNAME }}'
      POSTGRES_PASSWORD: '{{ GITLAB_DB_PASSWORD }}'
    networks:
      - gitlab
#   {% endif %}

networks:
  nginx:
    name: nginx
  gitlab:
    name: gitlab
