services:
  dsm:
    image: 'vdsm/virtual-dsm:{{ DSM_TAG }}'
    environment:
      DISK_SIZE: "{{ DSM_DISK_SIZE }}"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
#   {% if DSM_EXPOSE_PORT > 0 %}
    ports:
      - '{{ DSM_EXPOSE_PORT }}:5000'
#   {% endif %}
    volumes:
      - '{{ (APP_PATH/"data") | mkdir | chown }}:/storage'
#   {% for path in container.mount_paths %}
#      - '{{ path }}'
#   {% endfor %}
    restart: always
    stop_grace_period: 2m
    networks:
      - nginx

networks:
  nginx:
    name: nginx
