services:

  nextcloud:
    user: '{{ DOCKER_UID }}:{{ DOCKER_GID }}'
    environment:
      - 'NEXTCLOUD_DOMAIN={{ NEXTCLOUD_DOMAIN }}'
      - 'OVERWRITEPROTOCOL=https'
      - 'OVERWRITEHOST={{ NEXTCLOUD_DOMAIN }}:{{ HTTPS_PORT }}'
      - 'OVERWRITECLIURL=https://{{ NEXTCLOUD_DOMAIN }}:{{ HTTPS_PORT }}'
      - 'MAINTENANCE_WINDOW_START={{ NEXTCLOUD_MAINTENANCE_WINDOW_START }}'
      - 'MYSQL_DATABASE={{ NEXTCLOUD_MYSQL_DATABASE }}'
      - 'MYSQL_USER={{ NEXTCLOUD_MYSQL_USER }}'
      - 'MYSQL_PASSWORD={{ NEXTCLOUD_MYSQL_PASSWORD }}'
      - 'MYSQL_HOST=nextcloud_mariadb:3306'
      - 'REDIS_HOST=nextcloud_redis'
      - 'REDIS_PORT=6379'
      - 'REDIS_HOST_PASSWORD=nextcloud_redis_pass'
      - 'ONLYOFFICE_ENABLED={{ "yes" if NEXTCLOUD_ONLYOFFICE_ENABLED else "no" }}'
      - 'ONLYOFFICE_SECRET={{ NEXTCLOUD_ONLYOFFICE_SECRET }}'
      - 'ONLYOFFICE_HOST=nextcloud-onlyoffice'
  #   {% if NEXTCLOUD_PHP_MEMORY_LIMIT %}
      - 'PHP_MEMORY_LIMIT={{ NEXTCLOUD_PHP_MEMORY_LIMIT }}'
  #   {% endif %}
  #   {% if NEXTCLOUD_PHP_UPLOAD_LIMIT %}
      - 'PHP_UPLOAD_LIMIT={{ NEXTCLOUD_PHP_UPLOAD_LIMIT }}'
  #   {% endif %}
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0 # Allow an unprivileged user to listen on any port (https://github.com/nextcloud/docker/issues/359)
    volumes:
      - '{{ mkdir(APP_PATH/"html") | chown(docker_user) }}:/var/www/html'
      - '{{ mkdir(APP_PATH/"data") | chown(docker_user) }}:/var/www/html/data'
      - '{{ mkdir(USER_DATA_PATH) | chown(docker_user) }}:/data'
      - '{{ mkdir(DOWNLOAD_PATH) | chown(docker_user) }}:/downloads'
    networks:
      - nextcloud
      - nginx
    depends_on:
      - nextcloud-mariadb
      - nextcloud-redis
#   {% if NEXTCLOUD_ONLYOFFICE_ENABLED %}
      - nextcloud-onlyoffice
#   {% endif %}

  nextcloud-mariadb:
    image: mariadb
    user: '{{ DOCKER_UID }}:{{ DOCKER_GID }}'
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW --innodb-read-only-compressed=OFF
    environment:
      - 'MYSQL_ROOT_PASSWORD={{ NEXTCLOUD_MYSQL_ROOT_PASSWORD }}'
      - 'MYSQL_DATABASE={{ NEXTCLOUD_MYSQL_DATABASE }}'
      - 'MYSQL_USER={{ NEXTCLOUD_MYSQL_USER }}'
      - 'MYSQL_PASSWORD={{ NEXTCLOUD_MYSQL_PASSWORD }}'
    # ports:
    #   - 3306:3306
    hostname: nextcloud_mariadb
    volumes:
      - '{{ mkdir(APP_PATH/"mariadb") | chown(docker_user) }}:/var/lib/mysql'
    networks:
      - nextcloud

  nextcloud-redis:
    image: redis
    command: redis-server --requirepass nextcloud_redis_pass
    hostname: nextcloud_redis
    networks:
      - nextcloud

#   {% if NEXTCLOUD_ONLYOFFICE_ENABLED %}
  nextcloud-onlyoffice:
    image: onlyoffice/documentserver
    environment:
      - 'ONLYOFFICE_HTTPS_HSTS_ENABLED=false'
      - 'JWT_ENABLED=true'
      - 'JWT_HEADER=AuthorizationJwt'
      - 'JWT_SECRET={{ NEXTCLOUD_ONLYOFFICE_SECRET }}'
    volumes:
      - '{{ mkdir(APP_DATA_PATH/"onlyoffice") | chown }}:/var/www/onlyoffice/Data'
    networks:
      - nextcloud
      - nginx
#   {% endif %}

networks:
  nginx:
    name: nginx
  nextcloud:
    name: nextcloud
